### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by FloncDev** [FloncDev/exquisite-exoplanets#5]

**Comment by bensgilbert** [comment]
We need to store each user's:

- current script (and perhaps past scripts)
- points
- game progression/state

As a bonus we can also store

- interactivity
- signup date

Since we will be using FastAPI for the API, I vote for using SQLModel which is developed by the same person as the creator of FastAPI and it supports pydantic models. Naturally this means that the database would be SQL

**Comment by MilaDog** [comment]
SQLModel seems good. Haven't tried it out (mainly used the base shipped Pydantic, but can learn it).

From some brainstorming: 
![db_brainstorm](https://github.com/user-attachments/assets/c7f63e2e-e14d-4559-8bd0-b523232e8e8a)

**Comment by iauu** [comment]
I was thinking should we just use normal file storage for the user script?
```
- scripts (dir)
 - user_id1 (dir)
  - {script_id}.script (file)
```
and the database only store the reference to the active script by script\_id

**Comment by iauu** [comment]
This could further extend to the storing format for the field
```json
{
    "machine_type": [] // list of script_id
}
```
